apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: codenow-backstage-test1
  annotations:
    github.com/project-slug: kimrow/codenow-backstage-test1
    description: Microservice development platform for Containerized applications
  links:
    - url: 'https://example.com/docs'
      title: 'Documentation'
      icon: 'book'
    - url: 'https://example.com/repo'
      title: 'Repository'
      icon: 'code'
    - url: 'https://example.com/dashboard'
      title: 'Dashboard'
      icon: 'dashboard'
spec:
  lifecycle: development
  owner: codenow-customer
  type: platform
  