apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: codenow-backstage-test1
  annotations:
    github.com/project-slug: kimrow/codenow-backstage-test1
spec:
  lifecycle: production
  owner: codenow-customer
  type: service