apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: CodeNOW
  labels:
    tenant: 'cloud-dev.stxcn.codenow.com'
  annotations:
    github.com/project-slug: kimrow/codenow-backstage-test1
    description: Microservice development platform for Containerized applications
  links:
    - url: 'https://docs.codenow.com'
      title: 'Documentation'
      icon: 'book'
    - url: 'https://cloud.codenow.com'
      title: 'Self Service Portal'
      icon: 'code'
spec:
  lifecycle: development
  owner: field-sales-dept
  type: platform
  description: Microservice development platform for Containerized applications
  
